### ISSUE TITLE
Any plans for Version 3 of AWS SDK for PHP?

### ISSUE THREAD

**Issue by sfai05** [deliciousbrains/wp-amazon-web-services#72]

**Comment by A5hleyRich** [comment]
It's on the roadmap, but we don't have an ETA yet.

**Comment by ocasta** [comment]
Be good to have a version that uses a supported & fully HHVM compatible version of Guzzle

**Comment by fmoulton** [comment]
Any update on this ticket? This is getting into a must have situation especially for companies paying for WP Offload S3 and using v3 for other tasks. This ends up polluting the global name space.

**Comment by A5hleyRich** [comment]
Not at the moment.

**Comment by MWers** [comment]
@A5hleyRich From a paying (and otherwise very happy) customer, +1 on this... We're running WP inside containers on ECS and found that it's not possible to use IAM Roles for Tasks ([link](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html)) to manage permissions when using WP Offload S3 since IAM Roles for Tasks requires running v3.18.28+ of the PHP SDK. IAM Roles for EC2 Instances works but is an anti-pattern on ECS since it opens permissions to every container running on the ECS cluster and not the specific containers that need access. 

I'm guessing that it's a small subset of your customers running WP on ECS but here's hoping we see AWS SDK for PHP v3 support soon! :-)

**Comment by sampohaavisto** [comment]
I am using AWS SDK v3 in my app to load stuff from an external AWS account by assuming a role, signing the requests with SignatureV4 and finally handshaking with services built in the other AWS account.

It would be a shame forking the 👿 🔥  out of this plug-in.

Like @MWers, we currently have immutable servers and we might be running WP stuff in ECS in near future.

**Comment by sampohaavisto** [comment]
I ended up forking the aws-sdk and put it in Packagist with a namespace mod now pointing to `Aws3\` instead of `Aws\`. Still at testing phase but at least there's no more error messages from the plug-in.

**Comment by aaemnnosttv** [comment]
After much discussion, the team has decided that the safest way forward is for this plugin to stay on V2 of the AWS SDK for the foreseeable future. WP Offload S3 will soon no longer depend on this plugin as a dependency and include a prefixed version of the S3 SDK that it needs to prevent possible collisions with multiple versions. Once released, this plugin will no longer be required by our plugins and everyone will be free to deactivate this plugin and install whatever version of the AWS SDK they wish for their own use 🎉

**Comment by sampohaavisto** [comment]
@aaemnnosttv that's great news! Thank you.
