### ISSUE TITLE
DescribeJobFlows is deprecated

### ISSUE THREAD

**Issue by shackep** [deliciousbrains/wp-amazon-web-services#73]
Heads up: http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows.html

> This API is deprecated and will eventually be removed. We recommend you use ListClusters, DescribeCluster, ListSteps, ListInstanceGroups and ListBootstrapActions instead.

We have been notified by AWS that this is an issue that should be resolved.

> We are progressively removing customers from the whitelist every week based on number of calls and to ensure that we can reduce the customer impact. Please move away from the DescribeJobFlows Api as soon as possible.

Thanks!

**Comment by shackep** [comment]
https://github.com/deliciousbrains/wp-amazon-web-services/search?utf8=%E2%9C%93&q=DescribeJobFlows

**Comment by polevaultweb** [comment]
@shackep are you using the AWS plugin for DescribeJobFlows in another plugin?

**Comment by shackep** [comment]
I am only using WP Offload S3.

**Comment by aaemnnosttv** [comment]
This issue is really beyond the scope of this plugin, which simply includes the official AWS PHP SDK. The bundled version is the latest release of the v2 SDK (2.8.31). You may want to raise this issue on the [official repository](https://github.com/aws/aws-sdk-php/tree/2.8).

WP Offload S3 does not use EMR either so it sounds like you might be seeing something from another plugin's use anyways.
